test if examples are working (#11)
* test if examples are working

* setup protoc

* upgrade go

* try make examples not working

* Revert "try make examples not working"

This reverts commit 2ae08461cfa7627ebbf00049b841babdf648f0ec.

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -13,5 +13,19 @@ jobs:
     - uses: actions/checkout@v2
     - uses: actions/setup-go@v2
       with:
-        go-version: 1.16
-    - run: go test -v ./...
+        go-version: ^1.17
+    - uses: arduino/setup-protoc@v1
+    - name: test
+      run: go test -v ./...
+    - name: install
+      run: go install
+    - name: run examples
+      run: |
+        export PATH=$PATH:$(go env GOPATH)/bin
+        protoc example/user_add_comment.proto --pubsub-schema_out=.
+    - name: verify examples are working
+      run: |
+        if [ -n "$(git status --porcelain)" ]; then
+          git status # Show the files that failed to pass the check.
+          exit 1
+        fi
