test if examples are working

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -14,4 +14,17 @@ jobs:
     - uses: actions/setup-go@v2
       with:
         go-version: 1.16
-    - run: go test -v ./...
+    - name: test
+      run: go test -v ./...
+    - name: install
+      run: go install
+    - name: run examples
+      run: |
+        export PATH=$PATH:$(go env GOPATH)/bin
+        protoc example/user_add_comment.proto --pubsub-schema_out=.
+    - name: verify examples are working
+      run: |
+        if [ -n "$(git status --porcelain)" ]; then
+          git status # Show the files that failed to pass the check.
+          exit 1
+        fi
